### PR TITLE
Add shuffle support for LoongArch

### PR DESCRIPTION
**Pull request by lrzlin**
Add 128-bit shuffle operation support to LoongArch and fix compilation failure due to API changes. Tested on Loongson 3C5000 & Gentoo Linux.

Plus, I've notice that the atomic part has been rewritten, dropped the `fine-grained` only tag. so if LoongArch needs to add the `lr/sc` atomic support? If so, I'll do it as soon as possible.

### CODE REVIEW

**Comment by lrzlin** [comment]
BTW, LoongArch do not have macros like _ARM_FEATURE_ATOMICS by now. So if I want to add lr/sc style atomic operation, I have to use cpucfg at runtime in case of checking whether amcas instruction extension is available or not. Is that OK?

**Comment by carenas** [comment]
> use cpucfg at runtime

that would be similar to how `cpuid` is used in x86

**Comment by lrzlin** [comment]
> > use cpucfg at runtime
> 
> that would be similar to how `cpuid` is used in x86

Thanks, I'll check how x86 use it.

**Comment by zherczeg** [comment]
The lr/sc part is not necessary for all operations, the code generator can reject unsupported forms. Only the 32 bit / word sized operations are mandatory now.

**Comment by zherczeg** [comment]
Patch looks good. Shall I land it?

**Comment by lrzlin** [comment]
> The lr/sc part is not necessary for all operations, the code generator can reject unsupported forms. Only the 32 bit / word sized operations are mandatory now.

Got it, then I'll add 32 bit lr/sc support in a seperate patch for chips which doesn't support amcas. And how about this patch? Is there any issues?

**Comment by lrzlin** [comment]
> Patch looks good. Shall I land it?

Please do so, thanks.

**Review by zherczeg — APPROVED** [review]
LGTM

**Comment by zherczeg** [comment]
One more thing, the interface of simd instructions changed to use vreg (vector reg) instead of freg (float reg) because on some systems such as riscv the vector register set is independent from the float register set.

**Comment by lrzlin** [comment]
> One more thing, the interface of simd instructions changed to use vreg (vector reg) instead of freg (float reg) because on some systems such as riscv the vector register set is independent from the float register set.

I've noticed that, and Is it necessary to replace all 'FRD/FRJ/FRK' macros with 'VRD/VRJ/VRK' macros?

**Comment by zherczeg** [comment]
For private macros it is up to you. I didn't change them on some cpus, because they you a shared fpu/simd model.

**Comment by carenas** [comment]
Unrelated, but noticed the following when testing in an emulated archlinux with `gcc -fsanitize=undefined`:

```
$ bin/sljit_test -s
sljit_src/sljitNativeLOONGARCH_64.c:1223:29: runtime error: signed integer overflow: -7520595660820047966 - 9161432420001660707 cannot be represented in type 'long int'
sljit_src/sljitNativeLOONGARCH_64.c:1217:48: runtime error: signed integer overflow: -7520595660820047966 - 9161432420001660928 cannot be represented in type 'long int'
SLJIT tests: all tests PASSED on LOONGARCH 64bit (little endian + unaligned) (with simd)
```

**Comment by lrzlin** [comment]
> Unrelated, but noticed the following when testing in an emulated archlinux with `gcc -fsanitize=undefined`:
> 
> ```
> $ bin/sljit_test -s
> sljit_src/sljitNativeLOONGARCH_64.c:1223:29: runtime error: signed integer overflow: -7520595660820047966 - 9161432420001660707 cannot be represented in type 'long int'
> sljit_src/sljitNativeLOONGARCH_64.c:1217:48: runtime error: signed integer overflow: -7520595660820047966 - 9161432420001660928 cannot be represented in type 'long int'
> SLJIT tests: all tests PASSED on LOONGARCH 64bit (little endian + unaligned) (with simd)
> ```

I'll check this overflow error, thanks.

**Pull request merged**
