### PR TITLE
test: update test15 for 4 arguments

### PR DESCRIPTION
**Pull request by carenas**

### CODE REVIEW

**Comment by zherczeg** [comment]
What is the motivation of this patch? When I added the 4th arg support, I have added other tests for them. Is this better this way?

**Comment by carenas** [comment]
The use of a scratch register that was consecutive to the ones used to give parameters to the function called got me confused.

Still, adding a test with 4 parameters, and one that uses a different register and shows they are not overlapping is useful IMHO.

The typo fix is at least worth something.

**Comment by zherczeg** [comment]
The patch was good, and the current version is even better. I was just curious about the motivation. I can land it if you are ready.

**Comment by zherczeg** [comment]
Forgot to land this. Sorry

**Pull request merged**
