### PR TITLE
build: add barebones cmake for Windows

### PR DESCRIPTION
**Pull request by carenas**
While installing GNU make is usually not that difficult, this addresses a specific pain point of Windows developers without IMHO making it more difficult to support the build in other systems.

As a sideeffect, the renaming of the Makefile also helps BSD users that might accidentally invoke BSD make instead of `gmake` and be greeted with a syntax error.

### CODE REVIEW

**Comment by zherczeg** [comment]
Does this affect linux users?

**Comment by carenas** [comment]
If by "this" you mean the default stack size being too small to run sljit_test, then no.  AFAIK only Windows has 1MB stacks.

Using a 4MB stack instead of the default would also work in macOS and Linux, but I intentionally decided to add the logic only to the "cmake" file so it will most likely only be used in Windows.

**Comment by zherczeg** [comment]
I mean can you still build with "make" on Linux? The makefile is renamed.

**Comment by carenas** [comment]
> I mean can you still build with "make" on Linux? The makefile is renamed.

yes, GNU make will use the new name automatically.

**Comment by carenas** [comment]
> linux with musl libc (well known example is alpine linux) defaults to 128kb thread stacks. openbsd to 64kb even.

AFAIK OpenBSD has been using 512KB thread stack sizes for a few years already, but note that the restriction I was referring to wasn't per thread but per process, where mostly everyone (with 64-bit userspaces) provides at least 8MB by default.

**Comment by zherczeg** [comment]
I can land this patch if it is ready. However, I have no plans to work on many build systems unless the change is trivial.

**Review by zherczeg — APPROVED** [review]
LGTM

**Pull request merged**
